In [206]:
import sys, os, math, numpy as np, random
import pyproteinsExt.structure.coordinates as PDB
# sys.path.append("DockingPP")
from dockingPP import zParse
from rotation_utils import trans_matrix , eulerFromMatrix, vertical_matrix, equals
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [207]:
def equ(M1,M2): 
    for i in range(3): 
        for j in range(3):
            if not equals(M1[i,j],M2[i,j]): 
                print(M1[i,j])
                print(M2[i,j])
                return False
            
    return True

## Rotating functions

In [280]:
i=0
while i < 3000 : 
    angles=[random.uniform(-2* math.pi, 2* math.pi) for i in range(3)]
    # angles=[2.609046681938329, -3.5519708262845753, -5.34698673220635]
#     print(angles)
    M=trans_matrix(*angles)
#     print(M)
    # print(math.atan2(M[1,0],M[0,0]))
    # print(M[2,2]==-1)
    coords=vertical_matrix((2,5,7))
    # print(M.dot(coords))
    rep=eulerFromMatrix(M)
#     print(rep)
#     print(trans_matrix(*rep))
    # print(trans_matrix(*rep).dot(coords))
    # print((-2.5+1.67))
    if not equ(M,trans_matrix(*rep)) : 
        print(i)
        raise ValueError('OH OH')
        
    i+=1

-0.001117796172544608
-0.0011177961725324609
235


ValueError: OH OH

In [210]:
l = [3, 3]
array=np.empty(l)
print(array)
print(array[0,1])

[[-0.81383894 -0.57770637 -0.06262213]
 [-0.57877869  0.81548372 -0.00123757]
 [ 0.05178228  0.03523717 -0.99803654]]
-0.5777063657698421


In [188]:
DD=zParse("/Users/jprieto/Docking/data/decoys_bm4_zd3.0.2_6deg_fixed/results/1HIA.zd3.0.2.fg.fixed.out")
# print(DD.baryREC)
# print(DD.eulerREC)
DD.setReceptor("/Users/jprieto/Docking/data/decoys_bm4_zd3.0.2_6deg_fixed/input_pdbs/1HIA_r_u.pdb.ms_2")
DD.setLigand("/Users/jprieto/Docking/data/decoys_bm4_zd3.0.2_6deg_fixed/input_pdbs/1HIA_l_u.pdb.ms_2")


DD.pList[0].ccmap(dist=5)

    
C=DD.pList[0].resMapList

print(new_angles)
if unmatrix(trans_matrix(*new_angles))==new_angles: 
    print(unmatrix(trans_matrix(*new_angles)))
    print('OK')
else : 
    print(unmatrix(trans_matrix(*new_angles)))

NameError: name 'new_angles' is not defined

In [183]:
for atom in DD.pdbObjLigand.model[0]:
    initial_coords=(atom.x, atom.y, atom.z)
    a=trans_matrix(*DD.eulerREC)
    b=coord_matrix(DD.baryLIG, initial_coords)
#     print(initial_coords)
#     print(DD.baryLIG)
#     print(b)
    # print(b)
    coords=a.dot(b)
    center_coords=recenter(DD.baryLIG, coords)
    center_coords=recenter(DD.baryREC, coords)
    center_coords=translate_rev(DD.pList[0].translate,center_coords)
#     print(coords)
#     print(DD.baryLIG)
#     print(center_coords)
    atom.x=coords[0,0]
    atom.y=coords[1,0]
    atom.z=coords[2,0]
# print(DD.pdbObjLigand)

with open("new_1HIA_lig.pdb",'w') as f: 
    f.write(str(DD.pdbObjLigand))

In [131]:
def where(liste, str_cond) : 
    count=0
    for i in liste : 
        if str_cond in i : 
            count+=1
    return count

print(where(C,'Rec'))
print(where(C,'Lig'))
# print(DD.pList[0]._ccmap)

print(sorted([ i for i in C if 'Rec' in i]))

43
30
['102YRec', '141YRec', '151YRec', '152YRec', '153YRec', '154YRec', '193YRec', '194YRec', '195YRec', '196YRec', '197YRec', '212YRec', '213YRec', '214YRec', '32XRec', '33XRec', '34XRec', '35XRec', '36XRec', '38XRec', '39XRec', '40XRec', '41XRec', '42XRec', '43XRec', '54XRec', '55XRec', '56XRec', '57XRec', '58XRec', '59XRec', '60XRec', '61XRec', '62XRec', '63XRec', '64XRec', '66XRec', '70XRec', '71XRec', '72XRec', '73XRec', '74XRec', '75XRec']


# Test matrices

In [135]:
A=np.matrix([[1,1,1],[2,2,2],[3,3,3]])
X=np.matrix([[1],[2],[3]])
B=np.matrix([[1,2,3],[2,2,3],[4,3,2]])

In [193]:
e1=(1,1,0)
e2=(2*math.pi,2*math.pi,2*math.pi)

M1=trans_matrix(*e1)
M2=trans_matrix(*e2)

T=M2.dot(M1)

E=eulerFromMatrix(T)
print(E)

(0.9999999999999996, 0.9999999999999998, -2.4492935982947064e-16)


In [199]:
from matlab import eul2quat

ImportError: cannot import name 'eul2quat' from 'matlab' (/anaconda3/lib/python3.7/site-packages/matlab.py)